DATASET = {
    'first_names':[
        "Junko",
        "Pamila",
        "Doris",
        "Bo",
        "Erlene",
        "Armanda",
        "Susann",
        "Yulanda",
        "Calvin",
        "Sherlyn",
        "Latarsha",
        "Florencio",
        "Stefania",
        "Antione",
        "Minna",
        "Florine",
        "Bridget",
        "Matt",
        "Christoper",
        "Clotilde",
        "Teresa",
        "Gordon",
        "Luella",
        "Marianne",
        "Marlo",
        "Sherie",
        "Ben",
        "Vaughn",
        "Carylon",
        "Cathey"],
        
    'last_names':[
        "Smith",
        "Johnson",
        "Williams",
        "Jones",
        "Brown",
        "Davis",
        "Miller",
        "Wilson",
        "Moore",
        "Taylor",
        "Anderson",
        "Thomas",
        "Jackson",
        "White",
        "Harris",
        "Martin",
        "Thompson",
        "Garcia",
        "Martinez",
        "Robinson",
        "Clark",
        "Rodrigue",
        "Lewis",
        "Lee",
        "Walker",
        "Hall",
        "Allen",
        "Young",
        "Hernandez",
        "King"],

    'street_names':[
        "Grove",
        "Jackson",
        "Park",
        "Pennsylvania",
        "Adams",
        "Locust",
        "Madison",
        "5th",
        "Jefferson",
        "East",
        "Elizabeth",
        "Green",
        "Ridge",
        "11th",
        "12th",
        "Church",
        "Hill",
        "Lincoln",
        "River",
        "Route 30",
        "2nd Avenue",
        "4th",
        "Broadway",
        "Liberty",
        "3rd",
        "5th",
        "7th",
        "9th",
        "Dogwood",
        "Lincoln",
        "Meadow"],
    
    'street_types':[
        "St",
        "Rd",
        "Ln",
        "Ave",
        "Dr",
        "Tr",
        "Cr",
        "Blvd",
        "Cv"],
    
    'cities':[
        "New York^NY"
        "Los Angeles^CA",
        "Chicago^IL",
        "Houston^TX",
        "Philadelphia^PA",
        "Phoenix^AZ",
        "San Antonio^TX",
        "San Diego^CA",
        "Dallas^TX",
        "San Jose^CA",
        "Austin^TX",
        "Indianapolis^IN",
        "Jacksonville^FL",
        "San Francisco^CA",
        "Columbus^OH",
        "Charlotte^SC",
        "Fort Worth^TX",
        "Detroit^MI",
        "El Paso^TX",
        "Memphis^TN"],
        
    'race_codes':[
        "1002-5",
        "2028-9",
        "2054-5",
        "2076-8",
        "2106-3"],
    
    'resource_codes':[
        "1111^JLST",
        "2222^LOFM",
        "3333^URRT",
        "4444^YIPY",
        "5555^LTST",
        "6666^POLJ",
        "7777^QWER",
        "8888^OPAL",
        "9999^MEOW"],
    
    'location_codes':[
        "J36",
        "NAV",
        "14J",
        "J01",
        "J19",
        "J21",
        "J25",
        "J27",
        "J54",
        "J62",
        "J64",
        "JSC",
        "O01",
        "O02",
        "O03",
        "J22",
        "O04",
        "F01",
        "J24",
        "J23",
        "S12",
        "S01",
        "WPC",
        "J13",
        None],
    
    'personnel_codes':[
        "CBSK^KNIGHT MD^BARBARA^S",
        "TLLA^FAKE MD^NOTREAL^S",
        "PSPA^SPARKLES PHD^TINY^",
        "EJAH^SPEER MD^ELOIS^M",
        "ASDF^GARRISON MD^JENNIFER^V"]
        
        }
                

